### PR TITLE
bot_FlatterBaker603ye1.py

### PR DESCRIPTION
**Pull request by FlatterBaker603ye**
It uses the gambler's fallacy, even though it is a fallacy.

### CODE REVIEW

**Comment by cbscribe** [comment]
I'm afraid this code doesn't run. 

On line 6:
> Error in: FlatterBaker603ye1.py, cannot access local variable 'tim' where it is not associated with a value

**Comment by FlatterBaker603ye** [comment]
But I named the variable?

**Comment by cbscribe** [comment]
If the conditional statement on line 4 is false, then the variable isn't created at all, so on line 6 you can't add one to it.

**Comment by FlatterBaker603ye** [comment]
How do I change the file or do I upload a new one?

**Comment by cbscribe** [comment]
You can click on the "Files changed" above and then choose "edit" from the "..." menu in the top right to adjust your submission.

**Comment by FlatterBaker603ye** [comment]
I was able to edit the second submission but not the first, do I just submit another one?

**Pull request merged**
